// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXIWXtfIoeOPKbwC4n4k7wzL-ytEsPQOg',
    appId: '1:1017174093163:web:96963b3aa3d3b5b615302e',
    messagingSenderId: '1017174093163',
    projectId: 'belajar-c64d4',
    authDomain: 'belajar-c64d4.firebaseapp.com',
    storageBucket: 'belajar-c64d4.firebasestorage.app',
    measurementId: 'G-Y4CLS6PHHG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPG0QululsU0y7dbe_Rci2shbqcGLNqPs',
    appId: '1:1017174093163:android:84f6e7c50ca6cf4d15302e',
    messagingSenderId: '1017174093163',
    projectId: 'belajar-c64d4',
    storageBucket: 'belajar-c64d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEicjxgDr4jz1okWOWK5o7cRmQqYtkcEc',
    appId: '1:1017174093163:ios:748c34638ddf309215302e',
    messagingSenderId: '1017174093163',
    projectId: 'belajar-c64d4',
    storageBucket: 'belajar-c64d4.firebasestorage.app',
    iosBundleId: 'com.example.belajarFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEicjxgDr4jz1okWOWK5o7cRmQqYtkcEc',
    appId: '1:1017174093163:ios:748c34638ddf309215302e',
    messagingSenderId: '1017174093163',
    projectId: 'belajar-c64d4',
    storageBucket: 'belajar-c64d4.firebasestorage.app',
    iosBundleId: 'com.example.belajarFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXIWXtfIoeOPKbwC4n4k7wzL-ytEsPQOg',
    appId: '1:1017174093163:web:8f8e5423b2db615e15302e',
    messagingSenderId: '1017174093163',
    projectId: 'belajar-c64d4',
    authDomain: 'belajar-c64d4.firebaseapp.com',
    storageBucket: 'belajar-c64d4.firebasestorage.app',
    measurementId: 'G-ZEE6G2EKD1',
  );
}
